export const environment = {
  production: false,
  envName: 'dev',
  baseUrl: '',
  messenger_server_url: '',
  offloadUrl: '',
  admin_server_url: '',
  accounts_server_url: '',
  notification_server_url: '',
  notification_fallback_server_url: '',
  existing_url: '',
  domain_key: '',
  user_data_cookie_key: '',
  PORT: '',
  RELEASE_STAGE: '',
  DEPLOY_ID: '',
  SUBDOMAIN_MODIFIER: '',
  ALTERNATE: '',
  BASE_HREF: '',
  API_HOST: '',
  ASSET_HOST: '',
  SUPPORT_EMAIL: '',
  EMAIL_CONFIG_IID: 'ams'
};
